include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
- test
- deploy
- fedora

flatpak:
    needs: []
    variables:
        MANIFEST_PATH: "build-aux/flatpak/org.gnome.Connections.json"
        FLATPAK_MODULE: "connections"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.Connections.Devel"
        BUNDLE: "connections.flatpak"
    extends: .flatpak 

nightly:
  extends: '.publish_nightly'
  dependencies: ['flatpak']
  needs: ['flatpak']

fedora:latest:
    image: fedora:latest
    stage: fedora
    when: manual
    needs: []
    before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y meson git vala gtk3-devel
                     gtk-vnc2-devel gvncpulse-devel itstool gettext freerdp-devel
                     libhandy1-devel python3-devel libsecret-devel fuse3-devel --nogpgcheck

    script:
        - meson _build .
        - ninja -C _build
