include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
- test
- deploy
- fedora

variables:
    BUNDLE: "gnome-connections.flatpak"
    
flatpak:
    image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
    variables:
        MANIFEST_PATH: "build-aux/flatpak/org.gnome.Connections.json"
        FLATPAK_MODULE: "gnome-connections"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.Connections"
    extends: .flatpak 

fedora:rawhide:
    image: fedora:rawhide
    stage: fedora
    before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y meson git vala gtk3-devel
                     gtk-vnc2-devel gettext freerdp-devel
                     python3-devel --nogpgcheck

    script:
        - meson _build .
        - ninja -C _build
