include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
- test
- deploy
- fedora

flatpak:
    image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
    needs: []
    variables:
        MANIFEST_PATH: "build-aux/flatpak/org.gnome.Connections.json"
        FLATPAK_MODULE: "connections"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.Connections.Devel"
        BUNDLE: "connections.flatpak"
    extends: .flatpak 

nightly:
  extends: '.publish_nightly'
  dependencies: ['flatpak']
  needs: ['flatpak']
